<a href="https://colab.research.google.com/github/njwbilll/Tugas-5_Grokking-Deep-Learning-MANNING_Najwa-Bilqis-Al-Khalidah/blob/main/02_Fundamental_Concepts_How_Machines_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2: Fundamental Concepts: How Machines Learn

**Referensi:** Grokking Deep Learning, Andrew W. Trask (Manning Publications, 2019)

## Ringkasan Chapter

Chapter kedua mendalami paradigma paling mendasar yang menggerakkan seluruh arsitektur kecerdasan buatan dan deep learning. Penulis memperkenalkan tiga pilar utama dalam proses belajar mesin, yaitu Prediksi (Predict), Perbandingan (Compare), dan Pembelajaran (Learn). Siklus ini merupakan fondasi mutlak sebelum membangun jaringan saraf yang kompleks. Melalui konsep ini, kita memahami bagaimana sebuah sistem menerima informasi, mengukur tingkat kesalahan estimasinya, dan melakukan penyesuaian internal secara otomatis untuk mencapai akurasi optimal.

## Penjelasan Teori Siklus Utama

### 1. Fase Prediksi (Predict)
Fase prediksi adalah proses di mana model menerima data masukan (input) lalu melakukan operasi perkalian dengan parameter internal yang disebut bobot (weight). Bobot bertindak sebagai tingkat kepentingan atau skala pengaruh dari data masukan tersebut terhadap hasil akhir.

### 2. Fase Perbandingan (Compare)
Setelah nilai prediksi didapatkan, model tidak serta merta mengetahui apakah hasil tersebut sudah benar. Model memerlukan mekanisme untuk membandingkan hasil estimasi dengan target kebenaran absolut di dunia nyata. Indikator kuantitatif ini disebut sebagai nilai kesalahan (error) atau fungsi kerugian (loss function).

### 3. Fase Pembelajaran (Learn)
Fase pembelajaran merupakan konklusi dari siklus di mana model memanfaatkan informasi kesalahan dari fase perbandingan untuk memodifikasi nilai bobot. Perubahan dilakukan sedemikian rupa sehingga pada iterasi berikutnya, nilai kesalahan akan berangsur mengecil menuju titik nol.

### Tabel Koding 1: Inisialisasi Lingkungan Kerja dan Library
Langkah pertama adalah mempersiapkan pustaka NumPy sebagai satu satunya alat manipulasi matriks yang digunakan sepanjang buku ini untuk menjamin pemahaman tingkat rendah.

In [1]:
import numpy as np
print("Library NumPy berhasil dimuat untuk mendukung komputasi matriks.")

Library NumPy berhasil dimuat untuk mendukung komputasi matriks.


### Tabel Koding 2: Implementasi Fungsi Prediksi Tunggal Sederhana
Berikut adalah bentuk paling murni dari sebuah prediksi jaringan saraf, yaitu operasi perkalian linier antara satu titik input dengan satu parameter bobot.

In [2]:
def prediksi_tunggal(informasi_input, parameter_bobot):
    estimasi = informasi_input * parameter_bobot
    return estimasi

input_awal = 3.5
bobot_awal = 0.4
hasil_estimasi = prediksi_tunggal(input_awal, bobot_awal)
print("Hasil prediksi tunggal:", hasil_estimasi)

Hasil prediksi tunggal: 1.4000000000000001


### Tabel Koding 3: Prediksi Multivariat Manual dengan Perulangan
Ketika data masukan memiliki lebih dari satu variabel, kita harus mengalikan setiap elemen input dengan elemen bobot yang sesuai, kemudian menjumlahkan semuanya secara akumulatif.

In [3]:
def jumlah_bobot_manual(vektor_a, vektor_b):
    assert(len(vektor_a) == len(vektor_b))
    total_akumulasi = 0
    for indeks in range(len(vektor_a)):
        total_akumulasi += (vektor_a[indeks] * vektor_b[indeks])
    return total_akumulasi

kumpulan_input = [8.5, 9.5, 1.2]
kumpulan_bobot = [0.1, 0.2, 0.0]
prediksi_manual = jumlah_bobot_manual(kumpulan_input, kumpulan_bobot)
print("Hasil prediksi multivariat melalui loop manual:", prediksi_manual)

Hasil prediksi multivariat melalui loop manual: 2.75


### Tabel Koding 4: Prediksi Multivariat Memanfaatkan Vektorisasi NumPy
Perulangan manual sangat lambat untuk data besar. Jaringan saraf modern memanfaatkan operasi perkalian titik atau dot product yang dioptimalkan secara paralel oleh NumPy.

In [4]:
array_input = np.array([8.5, 9.5, 1.2])
array_bobot = np.array([0.1, 0.2, 0.0])
prediksi_numpy = np.dot(array_input, array_bobot)
print("Hasil prediksi multivariat dengan dot product NumPy:", prediksi_numpy)

Hasil prediksi multivariat dengan dot product NumPy: 2.75


### Tabel Koding 5: Mengukur Kesalahan Menggunakan Kuadrat Kesalahan (Squared Error)
Fungsi kuadrat kesalahan digunakan agar nilai simpangan selalu bernilai positif dan memberikan penalti yang jauh lebih besar bagi prediksi yang melenceng terlalu jauh.

In [5]:
def hitung_kuadrat_kesalahan(nilai_prediksi, nilai_target):
    selisih_mentah = nilai_prediksi - nilai_target
    return selisih_mentah * selisih_mentah

target_nyata = 1.0
nilai_kesalahan = hitung_kuadrat_kesalahan(prediksi_numpy, target_nyata)
print("Kuantitas kuadrat kesalahan model:", nilai_kesalahan)

Kuantitas kuadrat kesalahan model: 3.0625


### Tabel Koding 6: Eksperimen Awal Menggunakan Metode Hot and Cold
Metode Hot and Cold adalah strategi pembelajaran paling primitif dengan cara memodifikasi bobot sedikit ke atas dan sedikit ke bawah untuk melihat arah mana yang memperkecil nilai kesalahan.

In [6]:
skala_perubahan = 0.01
bobot_variasi_positif = array_bobot[0] + skala_perubahan
bobot_variasi_negatif = array_bobot[0] - skala_perubahan

print("Uji coba modifikasi bobot ke atas:", bobot_variasi_positif)
print("Uji coba modifikasi bobot ke bawah:", bobot_variasi_negatif)

Uji coba modifikasi bobot ke atas: 0.11
Uji coba modifikasi bobot ke bawah: 0.09000000000000001


### Tabel Koding 7: Proses Optimasi Iteratif dengan Skema Hot and Cold
Kita menjalankan perulangan untuk memaksa parameter bobot bergerak secara bertahap mendekati kombinasi ideal berdasarkan evaluasi variasi nilai kesalahan terkecil.

In [7]:
bobot_uji = 0.5
input_uji = 2.0
target_uji = 10.0
langkah_langkah = 0.1

for siklus in range(12):
    prediksi_saat_ini = input_uji * bobot_uji
    kesalahan_saat_ini = (prediksi_saat_ini - target_uji) ** 2

    prediksi_atas = input_uji * (bobot_uji + langkah_langkah)
    kesalahan_atas = (prediksi_atas - target_uji) ** 2

    prediksi_bawah = input_uji * (bobot_uji - langkah_langkah)
    kesalahan_bawah = (prediksi_bawah - target_uji) ** 2

    if kesalahan_atas < kesalahan_bawah:
        bobot_uji += langkah_langkah
    if kesalahan_bawah < kesalahan_atas:
        bobot_uji -= langkah_langkah

print("Nilai parameter bobot final pasca optimasi eksperimental:", bobot_uji)

Nilai parameter bobot final pasca optimasi eksperimental: 1.7000000000000004


### Tabel Koding 8: Intuitif Arah dan Magnitudo Pembaruan Berbasis Gradient Descent
Metode Hot and Cold tidak efisien karena harus menebak tebakan acak. Gradient Descent memecahkan hal ini dengan menghitung arah dan magnitudo perubahan secara eksak lewat perkalian antara selisih kesalahan dengan nilai input asli.

In [8]:
bobot_dasar = 0.5
input_spesifik = 4.0
target_spesifik = 8.0

prediksi_awal = input_spesifik * bobot_dasar
selisih_evaluasi = prediksi_awal - target_spesifik
skala_arah_magnitudo = selisih_evaluasi * input_spesifik
print("Nilai kalkulasi penunjuk arah dan magnitudo perubahan:", skala_arah_magnitudo)

Nilai kalkulasi penunjuk arah dan magnitudo perubahan: -24.0


### Tabel Koding 9: Penerapan Faktor Peredam Pembelajaran (Alpha)
Untuk mencegah perubahan bobot yang terlampau ekstrem yang dapat merusak konvergensi model, kita mengalikan magnitudo perubahan dengan sebuah pecahan kecil bernama tingkat pembelajaran atau alpha.

In [9]:
tingkat_alpha = 0.01
nilai_modifikasi = skala_arah_magnitudo * tingkat_alpha
bobot_terkoreksi = bobot_dasar - nilai_modifikasi
print("Nilai parameter bobot setelah dikoreksi dengan faktor alpha:", bobot_terkoreksi)

Nilai parameter bobot setelah dikoreksi dengan faktor alpha: 0.74


### Tabel Koding 10: Integrasi Siklus Utuh Prediksi, Perbandingan, dan Pembelajaran
Berikut adalah penggabungan seluruh komponen menjadi satu siklus utuh terintegrasi yang dijalankan secara otomatis dalam sepuluh tahapan waktu guna meminimalkan galat model secara konsisten.

In [10]:
bobot_operasional = 0.1
input_operasional = 2.0
target_operasional = 4.0
konstanta_alpha = 0.1
rekaman_historis = []

for generasi in range(1, 11):
    pred = input_operasional * bobot_operasional
    err = (pred - target_operasional) ** 2
    gradien = (pred - target_operasional) * input_operasional
    bobot_operasional = bobot_operasional - (konstanta_alpha * gradien)
    rekaman_historis.append([generasi, pred, err, bobot_operasional])

matriks_visualisasi = np.array(rekaman_historis)
print("Matriks laporan historis pelatihan (Kolom: Iterasi, Prediksi, Error, Bobot):")
print(matriks_visualisasi)

Matriks laporan historis pelatihan (Kolom: Iterasi, Prediksi, Error, Bobot):
[[1.00000000e+00 2.00000000e-01 1.44400000e+01 8.60000000e-01]
 [2.00000000e+00 1.72000000e+00 5.19840000e+00 1.31600000e+00]
 [3.00000000e+00 2.63200000e+00 1.87142400e+00 1.58960000e+00]
 [4.00000000e+00 3.17920000e+00 6.73712640e-01 1.75376000e+00]
 [5.00000000e+00 3.50752000e+00 2.42536550e-01 1.85225600e+00]
 [6.00000000e+00 3.70451200e+00 8.73131581e-02 1.91135360e+00]
 [7.00000000e+00 3.82270720e+00 3.14327369e-02 1.94681216e+00]
 [8.00000000e+00 3.89362432e+00 1.13157853e-02 1.96808730e+00]
 [9.00000000e+00 3.93617459e+00 4.07368271e-03 1.98085238e+00]
 [1.00000000e+01 3.96170476e+00 1.46652577e-03 1.98851143e+00]]
