<a href="https://colab.research.google.com/github/njwbilll/Tugas-5_Grokking-Deep-Learning-MANNING_Najwa-Bilqis-Al-Khalidah/blob/main/07_Picturing_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 7: Cara Membayangkan Jaringan Saraf Tiruan di Kepala dan di Atas Kertas

**Referensi:** Grokking Deep Learning, Andrew W. Trask (Manning Publications, 2019)

## Ringkasan Bab

Bab ketujuh mengajak pembaca untuk mengambil jeda dari rutinitas kalkulus yang rumit dan berfokus murni pada pemahaman konseptual serta visualisasi kecerdasan buatan. Menggambar jaringan dengan arsitektur kompleks menggunakan titik dan garis penghubung akan segera menjadi mustahil ketika jumlah parameter mencapai jutaan. Oleh karena itu, bab ini mengajarkan cara pandang baru yang lebih elegan yaitu dengan melihat susunan matriks parameter sebagai cermin pemantul korelasi atau cetakan memori. Dengan memvisualisasikan parameter secara langsung, kita dapat membuktikan bahwa mesin secara harfiah sedang menggambar ulang pola yang sering dilihatnya.

## Teori Inti Visualisasi Jaringan

### A. Menyederhanakan Diagram Abstrak
Pendekatan konvensional yang mengilustrasikan neuron sebagai lingkaran bola dan parameternya sebagai tali panjang sangat membebani imajinasi spasial kita. Buku ini mengarahkan kita untuk cukup membayangkan struktur data murni berupa kisi kisi angka. Sebuah proses konvolusi dapat dibayangkan secara sederhana sebagai proses menempelkan sebuah filter pencetak langsung ke atas data gambar asli.

### B. Peringkasan Korelasi Visual
Saat sebuah model dilatih membedakan berbagai bentuk objek, parameter pembobotnya tidak sekadar berisi angka acak. Parameter parameter tersebut perlahan menyesuaikan diri hingga wujud aslinya menyerupai bayangan objek tersebut. Jika suatu kelompok piksel sering menyala bersamaan di dalam gambar target, parameter model di posisi yang sama juga akan membesar secara sinkron.

### C. Pemanfaatan Representasi Karakter Teks
Untuk membedah otak kecerdasan buatan, kita tidak selalu memerlukan perangkat lunak perender grafik tinggi. Kita bisa menciptakan peta visual ringkas di atas terminal teks biasa dengan mengubah nilai nilai angka numerik yang besar dengan simbol yang mencolok, serta mengubah angka yang tidak relevan dengan ruang kosong.

### Tahap Pertama Persiapan Perangkat Komputasi
Kita memuat modul operasional aljabar untuk mengatur pembentukan susunan matriks data mentah.

In [1]:
import numpy as np
print("Modul manipulasi array telah bersiaga penuh untuk prosedur ekstraksi visual")

Modul manipulasi array telah bersiaga penuh untuk prosedur ekstraksi visual


### Desain Lingkungan Data Simulasi Optik
Untuk membuktikan teori visualisasi, kita meracik kumpulan gambar mini. Kumpulan pertama adalah bentuk bingkai kotak, dan kumpulan kedua adalah bentuk palang silang. Seluruh data diratakan menjadi vektor baris tunggal agar mudah dikonsumsi oleh algoritma.

In [2]:
citra_bingkai_kotak = np.array([
    [1, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
]).flatten()

citra_palang_silang = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
]).flatten()

gudang_koleksi_data = np.array([citra_bingkai_kotak, citra_palang_silang])
sasaran_identifikasi = np.array([[1], [0]])

print("Bentuk struktur matriks koleksi data prapelatihan:", gudang_koleksi_data.shape)

Bentuk struktur matriks koleksi data prapelatihan: (2, 9)


### Siklus Asimilasi Penurunan Gradien Intensif
Kita memberikan instruksi kepada otak buatan ini untuk mendeteksi hanya gambar yang memiliki bentuk kotak. Seiring berjalannya putaran perulangan, parameter murni akan berusaha memahat esensi visual dari bingkai kotak tersebut ke dalam ingatannya sendiri.

In [3]:
np.random.seed(99)
ingatan_kognitif = 2 * np.random.random((9, 1)) - 1
skala_pembelajaran = 0.1

for siklus_penglihatan in range(50):
    untuk_kalkulasi_error = 0

    for posisi_indeks in range(len(gudang_koleksi_data)):
        fakta_visual = gudang_koleksi_data[posisi_indeks:posisi_indeks+1]
        kebenaran_hakiki = sasaran_identifikasi[posisi_indeks:posisi_indeks+1]

        tanggapan_model = np.dot(fakta_visual, ingatan_kognitif)

        simpangan_realitas = tanggapan_model - kebenaran_hakiki
        ingatan_kognitif -= skala_pembelajaran * (np.dot(fakta_visual.T, simpangan_realitas))

        untuk_kalkulasi_error += np.sum(simpangan_realitas ** 2)

print("Jaringan berhasil menyerap materi optik secara tuntas")

Jaringan berhasil menyerap materi optik secara tuntas


### Operasi Pembedahan Memori Kognitif
Sesuai arahan utama dalam bab ketujuh, keajaiban sesungguhnya terlihat ketika kita mengembalikan vektor memori panjang tersebut kembali ke dalam wujud kotak simetris lalu mengamatinya.

In [4]:
memori_terekonstruksi = ingatan_kognitif.reshape((3, 3))

print("Distribusi angka murni di dalam benak kecerdasan buatan:")
print(np.round(memori_terekonstruksi, 2))

Distribusi angka murni di dalam benak kecerdasan buatan:
[[ 0.03  0.58  0.33]
 [-0.33 -0.31  0.74]
 [-0.72 -0.3   0.67]]


### Translasi Pikiran Mesin Menjadi Teks Simbolik
Membaca angka desimal sungguh melelahkan bagi mata manusia. Kita menulis sebuah jembatan penerjemah yang mengubah angka dominan positif menjadi simbol cetak tebal, sementara angka yang melemah atau negatif disulap menjadi titik samar.

In [5]:
def proyektor_mental(kisi_kisi_memori):
    kanvas_layar = ""
    for urutan_baris in kisi_kisi_memori:
        for butiran_nilai in urutan_baris:
            if butiran_nilai > 0.4:
                kanvas_layar += "# "
            elif butiran_nilai < -0.1:
                kanvas_layar += ". "
            else:
                kanvas_layar += "  "
        kanvas_layar += "\n"
    return kanvas_layar

print("Bukti empiris bahwa mesin mereplika pola bingkai sasaran di dalam benaknya sendiri:")
print(proyektor_mental(memori_terekonstruksi))

print("Bisa diamati secara nyata bahwa simbol pagar membentuk batas luar kotak persis menyerupai korelasi data asli")

Bukti empiris bahwa mesin mereplika pola bingkai sasaran di dalam benaknya sendiri:
  #   
. . # 
. . # 

Bisa diamati secara nyata bahwa simbol pagar membentuk batas luar kotak persis menyerupai korelasi data asli
